---
- name: 'Backend Server'
  hosts: default
  become: true
  remote_user: root
  vars:
    ansible_remote_tmp: /tmp

  pre_tasks:
    - name: Update system to latest
      apt:
        update_cache: true
        upgrade: dist
    - name: Install ca-certificates
      apt:
        name: ca-certificates
        state: present
    - name: Update ca certificates
      ansible.builtin.command:
        cmd: update-ca-certificates

  tasks:
    - name: Create Docker stack config folder
      ansible.builtin.file:
        path: /var/www/roe
        state: directory
        owner: root
        group: root
        mode: 755
    - name: Install net-tools
      apt:
        name: net-tools
        state: present
    - name: Install vim
      apt:
        name: vim
        state: present
    - name: Install rsync
      apt:
        name: rsync
        state: present
    - name: Install python3-docker
      apt:
        name: python3-docker
        state: present

  roles:
    - role: geerlingguy.pip
      vars:
        pip_install_packages:
          - name: docker
          - name: docker-compose
    - role: geerlingguy.docker
      docker_install_compose: true
    - role: geerlingguy.security
      security_ssh_permit_root_login: "yes"
      security_autoupdate_reboot: true

