CREATE TABLE report (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_datetime TIMESTAMP NOT NULL DEFAULT NOW(),
    app_name TEXT NOT NULL,
    screenshot TEXT,
    username_report TEXT,
    username_suspect TEXT
);