CREATE TABLE report (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_datetime TIMESTAMP NOT NULL DEFAULT NOW(),
    platform TEXT NOT NULL,
    screenshot TEXT,
    username_report TEXT NOT NULL,
    username_suspect TEXT NOT NULL,
    ip_address TEXT
);