services:

  postgres:
    image: postgres:14-alpine
    restart: always
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - "POSTGRES_DB=roe"
      - "POSTGRES_USER=roe"
      - "POSTGRES_PASSWORD"

  hasura:
    image: hasura/graphql-engine:latest
    ports:
      - "8081:8080"
    restart: always
    networks:
      - default
      - roe
    environment:
      - "HASURA_GRAPHQL_DATABASE_URL=postgres://roe:${POSTGRES_PASSWORD}@postgres:5432/roe?sslmode=disable"
      - "HASURA_GRAPHQL_ENABLE_CONSOLE=true"
      - "HASURA_GRAPHQL_ENABLE_TELEMETRY=false"
      - "HASURA_GRAPHQL_UNAUTHORIZED_ROLE=noauth"
      - "HASURA_GRAPHQL_CORS_DOMAIN=*"
      - "HASURA_GRAPHQL_ADMIN_SECRET"

volumes:
  db:

networks:
  roe:
    external: true
